[package]
name = "itch-lite"
version = "0.1.0"
authors = ["A. Nonymous Wenger <fasterthanlime@gmail.com>"]
edition = "2018"

[dependencies]
web-view = { version = "0.5.3", features = ["edge"] }

[profile.release]
lto = true
