[package]
name = "itch-lite"
version = "0.1.0"
authors = ["A. Nonymous Wenger <fasterthanlime@gmail.com>"]
edition = "2018"

[dependencies]
# note: edge can't build on Win2012 it's only Win10
web-view = { version = "0.5.3", features = [] }

[profile.release]
lto = true
