[package]
name = "itch-lite"
version = "0.1.0"
authors = ["A. Nonymous Wenger <fasterthanlime@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
tether = { path = "./vendor/tether" }
env_logger = "0.7.1"
log = "0.4.8"
